using System;
using System.Text.RegularExpressions;
using System.Diagnostics;

var text = @"thinker-test
    import-s3-export-rds
  nnlife_s3_to_td
    nnlife_s3_to_td
  nnlife_CV_request_form_s3_to_td
    nnlife_CV_request_form_s3_to_td
  nnlife_CV_enquiry_form_s3_to_td
    nnlife_CV_enquiry_form_s3_to_td
  nnlife_latest_ad_report
    nnlife_latest_ad_report
  nnlife_etl_perfomance_analysis
    nnlife_etl_perfomance_analysis
  nnlife_merge_tables_to_analyzed_ad_report
    nnlife_merge_tables_to_analyzed_ad_report
  nasdaq_analysis
    nasdaq_analysis
  tsuboi_practice_wf
    tsuboi_practice_wf
  test-puma-nakasuji
    test-puma-nakasuji
  simple-example
    simple
  zurich_s3_load
    zurich_s3_load
  zurich_attribution_analysis_202103
    zurich_attribution_analysis_202103
  fabric_tokyo_fb_conversion_api_wf
    fabric_tokyo_fb_conversion_api_wf
  tatanic_practice
    tatanic_practice
  cdp_audience_1520
    predictive_scoring
    metering_audience
    audience
    sisense_data_ingestion
  cdp_audience_164949
    predictive_scoring
    metering_audience
    audience
    sisense_data_ingestion
  cdp_audience_958
    predictive_scoring
    metering_audience
    audience
    sisense_data_ingestion
  cdp_segment_2190
    syndication_719
  cdp_segment_2191
    syndication_718
  cdp_audience_166398
    predictive_scoring
    metering_audience
    audience
    sisense_data_ingestion
  cdp_audience_166229
    predictive_scoring
    metering_audience
    audience
    sisense_data_ingestion
  zurich_attribution_202109
    zurich_attribution_202109
  zurich_withdrawal_analytics_20210908
    zurich_withdrawal_analytics_20210908
  fabric_tokyo_members_wf
    fabric_tokyo_members_wf
  yamanaka_zurichi_spreadsheet_wf_test
    yamanaka_zurichi_spreadsheet_wf_test
  fabric_tokyo_attribution_1
    fabric_tokyo_attribution_1
  fabric_tokyo_attribution_parameter_cnt
    fabric_tokyo_attribution_parameter_cnt
  yamanaka_zurich_report_wf
    yamanaka_zurich_report_wf
  naka_etudie3
    naka_etudie3
  UCC_python
    UCC_python
  tsuboi_zurich_report_wf
    tsuboi_zurich_report_wf
  yamanaka_zurich_report_2_wf
    yamanaka_zurich_report_2_wf
  yamanaka_puma_first_time_purchase_predict
    yamanaka_puma_first_time_purchase_predict
  Puma-python-tsuboi
    Puma-python-tsuboi
  Puma-python-ogino
    Puma-python-ogino
  cdp_audience_244297
    audience
    metering_audience
    predictive_scoring
    sisense_data_ingestion
  zurich_s3_load_recovery
    zurich_s3_load_recovery
  zurich_ad_report_extra
    zurich_ad_report_extra
  yamanaka_zurich_reprot_wf
    yamanaka_zurich_reprot_wf
  kubo_test
    kubo_test
  fabric_tokyo_td2b_dash_wf
    fabric_tokyo_td2b_dash_wf
  FT_20220315_store_analysis
    FT_20220315_store_analysis
  huang_formaltest0411
    huang_formaltest0411
  quick_test
    quick_test
  yamanaka_aa_app_load_test
    yamanaka_aa_app_load_test
  yamanaka_zurich_reprot_temp_wf
    yamanaka_zurich_reprot_temp_wf
  fabric_tokyo_td2b_dash_wf_test
    fabric_tokyo_td2b_dash_wf_test
  ft_firsttimebuy_prediction_renewal_huang0425
    ft_firsttimebuy_prediction_renewal_huang0425
  FT_firsttimebuy_predict
    FT_firsttimebuy_predict
  huang_select_last_results_test0427
    huang_select_last_results_test0427
  huang_partial_delete_test0513
    huang_partial_delete_test0513
  yamanaka_cmd_test_wf
    yamanaka_cmd_test_wf
  fabric_tokyo_td2bdash_canceled_reservation
    fabric_tokyo_td2bdash_canceled_reservation
  zurich_ad_report
    zurich_ad_report
  huang_zurichadreport_renewal_20220627
    huang_zurichadreport_renewal_20220627
  twitter2td_20220624
    twitter2td_20220624
  better_sfdc2td_daily_load_wf
    better_sfdc2td_daily_load_wf
  fabric_tokyo_latest_tables
    fabric_tokyo_latest_tables
  fabric_tokyo_create_mart
    fabric_tokyo_create_mart
  kubo_sample220808
    kubo_sample220808
  torikoshi_sample_20220808
    torikoshi_sample_20220808
  cdp_audience_291337
    metering_audience
    audience
    sisense_data_ingestion
    predictive_scoring
  yamanaka_sample_wf
    yamanaka_sample_wf
  Myamaguchi_sample220808
    Myamaguchi_sample220808
  cdp_audience_291556
    metering_audience
    audience
    sisense_data_ingestion
    predictive_scoring
";
var with2space = new Regex(@"^\s\s", RegexOptions.Multiline);

var hyphenedWord =
    from Match m in with2space.Matches(text)
    select m.Value;

foreach (var item in hyphenedWord)
{
    Console.WriteLine(item);
}