# For more advanced config options, please check these URLs.
# @see https://docs.treasuredata.com/articles/data-connector-amazon-s3
# @see https://github.com/embulk/embulk-input-s3
---
in:
  type: s3
  endpoint: s3-ap-northeast-1.amazonaws.com
  access_key_id: AKIAJ6D44F2AVIVIKMDQ
  secret_access_key: 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
  bucket: td-workflow-test
  path_prefix: rentracks
  parser:
    charset: Shift_JIS
    newline: CRLF
    type: csv
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: orner_id, type: long}
    - {name: site_id, type: long}
    - {name: site_name, type: string}
    - {name: site_url, type: string}
    - {name: displya_count, type: long}
    - {name: click_count, type: long}
    - {name: ctr, type: double}
    - {name: vor, type: double}
    - {name: cor, type: double}
    - {name: revenue_count, type: long}
    - {name: pennding_count, type: long}
    - {name: rejected_count, type: long}
    - {name: approved_count, type: long}
    - {name: billed_count, type: long}
    - {name: reward, type: long}
    - {name: pennding, type: long}
    - {name: rejected, type: long}
    - {name: approved, type: long}
    - {name: billed, type: long}
    - {name: created, type: timestamp, format: "%Y-%m-%d %H:%M:%S"}
out:
  mode: append